name: Functional Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
      
      - name: Change directory
        run: cd functional_tests

      - name: Install dependencies
        run: npm ci

      - name: Run Webdriver.io tests
        run: npx wdio run ./wdio.conf.ts